import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Libre_Baskerville } from 'next/font/google';

const libre = Libre_Baskerville({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col items-center ${libre.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
